"use client"

import type { Metadata } from "next";
import "./globals.css";
import { Inter } from "next/font/google";

import AuthProvider from "@/components/auth/AuthProvider";
import Header from "@/components/ui/Header";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "UBERMENSCH",
  description: "Generated by gary",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} bg-secondary`}
      >
        <AuthProvider>
          <Header />
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
